// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmzvnugknvokvldhketf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtenZudWdrbnZva3ZsZGhrZXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDkwMDEsImV4cCI6MjA2OTg4NTAwMX0.cBanokDnm1OQ1q8iO_WR79-3U5rTsdRpvx5TUxANhNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});